### ISSUE TITLE
Add Search Field

### ISSUE THREAD

**Issue by tsukuros** [vlasenkosi/contact-book#3]
We need a way to search contacts.

**Comment by vlasenkosi** [comment]
Done.....

**Comment by tsukuros** [comment]
1. Could you please make search look more decent like a small one here http://jsfiddle.net/KyleMit/cyCFS/ - Add Bootstrap styling
2. I like that you added select element but we don't need multi-select option, please make it a single select(plain old select) - Add Bootstrap styling

**Comment by vlasenkosi** [comment]
Changed.

Now i am working on user info.

**Comment by ghost** [comment]
:+1:
